logging:
  level:
    com.gargoylesoftware.htmlunit: ERROR

htmlscraping:
  timeout: 5000

server:
  port: ${PORT:2000}

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

eureka:
  instance:
    non-secure-port: 80
    metadata-map.instanceId: ${vcap.application.instance_id}
    hostname: ${vcap.application.uris[0]:http://localhost:2000}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localhost:8761}/eureka/
